const Posts = [
  {
    id: 1,
    userPhoto: "/assets/user.png",
    userName: "tracymcgrady",
    Photo: "/assets/post1.jpg",
    noOfLikes: 32,
    caption: "lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    hashTags: "#iphone #cases #mobile #macbookpro",
    noOfComments: 12,
    fav: false,
  },
  {
    id: 2,
    userPhoto: "/assets/user.png",
    userName: "EmilyJohnson",
    Photo: "/assets/post2.jpg",
    noOfLikes: 27,
    caption: "Nulla eget ligula sagittis, vehicula mi at, facilisis metus.",
    hashTags: "#iphone #cases #mobile #macbookpro",
    noOfComments: 16,
    fav: false,
  },
  {
    id: 3,
    userPhoto: "/assets/user.png",
    userName: "BenjaminDavis",
    Photo: "/assets/post3.jpg",
    noOfLikes: 84,
    caption:
      "Praesent cursus sem et nisl vestibulum, vitae tincidunt quam feugiat.",
    hashTags: "#iphone #cases #mobile #macbookpro",
    noOfComments: 42,
    fav: false,
  },
  {
    id: 4,
    userPhoto: "/assets/user.png",
    userName: "NoahTaylor",
    Photo: "/assets/post4.jpg",
    noOfLikes: 51,
    caption: "Sed tincidunt nulla vel semper convallis.",
    hashTags: "#iphone #cases #mobile #macbookpro",
    noOfComments: 34,
    fav: false,
  },
  {
    id: 5,
    userPhoto: "/assets/user.png",
    userName: "IsabellaLewis",
    Photo: "/assets/post5.jpg",
    noOfLikes: 62,
    caption:
      "Vestibulum condimentum ante ac neque accumsan, ut auctor quam tristique.",
    hashTags: "#iphone #cases #mobile #macbookpro",
    noOfComments: 19,
    fav: false,
  },
  {
    id: 6,
    userPhoto: "/assets/user.png",
    userName: "JamesMitchell",
    Photo: "/assets/post6.jpg",
    noOfLikes: 94,
    caption: "Nunc auctor lacus id est tempus, ac mattis metus condimentum.",
    hashTags: "#iphone #cases #mobile #macbookpro",
    noOfComments: 15,
    fav: false,
  },
  {
    id: 7,
    userPhoto: "/assets/user.png",
    userName: "MiaRoberts",
    Photo: "/assets/post7.jpg",
    noOfLikes: 12,
    caption: "Curabitur et eros blandit, fermentum massa vel, convallis purus.",
    hashTags: "#iphone #cases #mobile #macbookpro",
    noOfComments: 9,

    fav: false,
  },
  {
    id: 8,
    userPhoto: "/assets/user.png",
    userName: "OliviaAnderson",
    Photo: "/assets/post8.jpg",
    noOfLikes: 45,
    caption: "Fusce ac odio id odio ultricies ultricies.",
    hashTags: "#iphone #cases #mobile #macbookpro",
    noOfComments: 4,

    fav: false,
  },
  {
    id: 9,
    userPhoto: "/assets/user.png",
    userName: "EthanThompson",
    Photo: "/assets/post9.jpg",
    noOfLikes: 61,
    caption: "lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    hashTags: "#iphone #cases #mobile #macbookpro",
    noOfComments: 23,
    fav: false,
  },
  {
    id: 10,
    userPhoto: "/assets/user.png",
    userName: "AvaMartinez",
    Photo: "/assets/post10.jpg",
    noOfLikes: 120,
    caption: "Nulla eget ligula sagittis, vehicula mi at, facilisis metus.",
    hashTags: "#iphone #cases #mobile #macbookpro",
    noOfComments: 50,
    fav: false,
  },
  {
    id: 11,
    userPhoto: "/assets/user.png",
    userName: "LiamWilson",
    Photo: "/assets/post11.jpg",
    noOfLikes: 20,
    caption:
      "Praesent cursus sem et nisl vestibulum, vitae tincidunt quam feugiat.",
    hashTags: "#iphone #cases #mobile #macbookpro",
    noOfComments: 6,

    fav: false,
  },
  {
    id: 12,
    userPhoto: "/assets/user.png",
    userName: "AlexanderWalker",
    Photo: "/assets/post12.jpg",
    noOfLikes: 32,
    caption: "Curabitur et eros blandit, fermentum massa vel, convallis purus",
    hashTags: "#iphone #cases #mobile #macbookpro",
    noOfComments: 12,
    fav: false,
  },
  {
    id: 13,
    userPhoto: "/assets/user.png",
    userName: "SophiaClark",
    Photo: "/assets/post13.jpg",
    noOfLikes: 72,
    caption: "Sed tincidunt nulla vel semper convallis.",
    hashTags: "#iphone #cases #mobile #macbookpro",
    noOfComments: 14,
    fav: false,
  },
  {
    id: 14,
    userPhoto: "/assets/user.png",
    userName: "CharlotteTurner",
    Photo: "/assets/post14.jpg",
    noOfLikes: 38,
    caption: "lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    hashTags: "#iphone #cases #mobile #macbookpro",
    noOfComments: 10,
    fav: false,
  },
  {
    id: 15,
    userPhoto: "/assets/user.png",
    userName: "JacobGarcia",
    Photo: "/assets/post15.jpg",
    noOfLikes: 53,
    caption: "Nulla eget ligula sagittis, vehicula mi at, facilisis metus.",
    hashTags: "#iphone #cases #mobile #macbookpro",
    noOfComments: 22,
    fav: false,
  },
];

export default Posts;
