import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import { FaHeart, FaHome } from "react-icons/fa";
import style from "./styles/style.module.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={style.navbar}>
          <p href="" className={style.title}>
            Instagram
          </p>
          <div>
            <Link href="./" style={{ textdecoration: "none" }}>
              Home
            </Link>
            <Link href="./favourite-page">Favourite</Link>
            <Link href="">Logout</Link>
          </div>
        </div>
        {children}
        <div className={style.footer}>
          <Link href="./" style={{ textdecoration: "none" }}>
            <FaHome />
          </Link>
          <Link href="./favourite-page">
            <FaHeart />
          </Link>
        </div>
      </body>
    </html>
  );
}
